package com.implementsfun.protoj;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filter_message.proto

public final class FilterMessage {
  private FilterMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Filter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double max_price_usd = 1;</code>
     * @return The maxPriceUsd.
     */
    double getMaxPriceUsd();

    /**
     * <code>uint32 min_cpu_cores = 2;</code>
     * @return The minCpuCores.
     */
    int getMinCpuCores();

    /**
     * <code>double min_cpu_ghz = 3;</code>
     * @return The minCpuGhz.
     */
    double getMinCpuGhz();

    /**
     * <code>.Memory min_ram = 4;</code>
     * @return Whether the minRam field is set.
     */
    boolean hasMinRam();
    /**
     * <code>.Memory min_ram = 4;</code>
     * @return The minRam.
     */
    MemoryMessage.Memory getMinRam();
    /**
     * <code>.Memory min_ram = 4;</code>
     */
    MemoryMessage.MemoryOrBuilder getMinRamOrBuilder();
  }
  /**
   * Protobuf type {@code Filter}
   */
  public static final class Filter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Filter)
      FilterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Filter.newBuilder() to construct.
    private Filter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Filter() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Filter();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Filter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              maxPriceUsd_ = input.readDouble();
              break;
            }
            case 16: {

              minCpuCores_ = input.readUInt32();
              break;
            }
            case 25: {

              minCpuGhz_ = input.readDouble();
              break;
            }
            case 34: {
              MemoryMessage.Memory.Builder subBuilder = null;
              if (minRam_ != null) {
                subBuilder = minRam_.toBuilder();
              }
              minRam_ = input.readMessage(MemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(minRam_);
                minRam_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FilterMessage.internal_static_Filter_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FilterMessage.internal_static_Filter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Filter.class, Builder.class);
    }

    public static final int MAX_PRICE_USD_FIELD_NUMBER = 1;
    private double maxPriceUsd_;
    /**
     * <code>double max_price_usd = 1;</code>
     * @return The maxPriceUsd.
     */
    @Override
    public double getMaxPriceUsd() {
      return maxPriceUsd_;
    }

    public static final int MIN_CPU_CORES_FIELD_NUMBER = 2;
    private int minCpuCores_;
    /**
     * <code>uint32 min_cpu_cores = 2;</code>
     * @return The minCpuCores.
     */
    @Override
    public int getMinCpuCores() {
      return minCpuCores_;
    }

    public static final int MIN_CPU_GHZ_FIELD_NUMBER = 3;
    private double minCpuGhz_;
    /**
     * <code>double min_cpu_ghz = 3;</code>
     * @return The minCpuGhz.
     */
    @Override
    public double getMinCpuGhz() {
      return minCpuGhz_;
    }

    public static final int MIN_RAM_FIELD_NUMBER = 4;
    private MemoryMessage.Memory minRam_;
    /**
     * <code>.Memory min_ram = 4;</code>
     * @return Whether the minRam field is set.
     */
    @Override
    public boolean hasMinRam() {
      return minRam_ != null;
    }
    /**
     * <code>.Memory min_ram = 4;</code>
     * @return The minRam.
     */
    @Override
    public MemoryMessage.Memory getMinRam() {
      return minRam_ == null ? MemoryMessage.Memory.getDefaultInstance() : minRam_;
    }
    /**
     * <code>.Memory min_ram = 4;</code>
     */
    @Override
    public MemoryMessage.MemoryOrBuilder getMinRamOrBuilder() {
      return getMinRam();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Double.doubleToRawLongBits(maxPriceUsd_) != 0) {
        output.writeDouble(1, maxPriceUsd_);
      }
      if (minCpuCores_ != 0) {
        output.writeUInt32(2, minCpuCores_);
      }
      if (Double.doubleToRawLongBits(minCpuGhz_) != 0) {
        output.writeDouble(3, minCpuGhz_);
      }
      if (minRam_ != null) {
        output.writeMessage(4, getMinRam());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Double.doubleToRawLongBits(maxPriceUsd_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, maxPriceUsd_);
      }
      if (minCpuCores_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, minCpuCores_);
      }
      if (Double.doubleToRawLongBits(minCpuGhz_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, minCpuGhz_);
      }
      if (minRam_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMinRam());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Filter)) {
        return super.equals(obj);
      }
      Filter other = (Filter) obj;

      if (Double.doubleToLongBits(getMaxPriceUsd())
          != Double.doubleToLongBits(
              other.getMaxPriceUsd())) return false;
      if (getMinCpuCores()
          != other.getMinCpuCores()) return false;
      if (Double.doubleToLongBits(getMinCpuGhz())
          != Double.doubleToLongBits(
              other.getMinCpuGhz())) return false;
      if (hasMinRam() != other.hasMinRam()) return false;
      if (hasMinRam()) {
        if (!getMinRam()
            .equals(other.getMinRam())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAX_PRICE_USD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMaxPriceUsd()));
      hash = (37 * hash) + MIN_CPU_CORES_FIELD_NUMBER;
      hash = (53 * hash) + getMinCpuCores();
      hash = (37 * hash) + MIN_CPU_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMinCpuGhz()));
      if (hasMinRam()) {
        hash = (37 * hash) + MIN_RAM_FIELD_NUMBER;
        hash = (53 * hash) + getMinRam().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Filter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Filter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Filter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Filter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Filter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Filter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Filter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Filter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Filter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Filter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Filter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Filter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Filter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Filter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Filter)
        FilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FilterMessage.internal_static_Filter_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FilterMessage.internal_static_Filter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Filter.class, Builder.class);
      }

      // Construct using FilterMessage.Filter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        maxPriceUsd_ = 0D;

        minCpuCores_ = 0;

        minCpuGhz_ = 0D;

        if (minRamBuilder_ == null) {
          minRam_ = null;
        } else {
          minRam_ = null;
          minRamBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FilterMessage.internal_static_Filter_descriptor;
      }

      @Override
      public Filter getDefaultInstanceForType() {
        return Filter.getDefaultInstance();
      }

      @Override
      public Filter build() {
        Filter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Filter buildPartial() {
        Filter result = new Filter(this);
        result.maxPriceUsd_ = maxPriceUsd_;
        result.minCpuCores_ = minCpuCores_;
        result.minCpuGhz_ = minCpuGhz_;
        if (minRamBuilder_ == null) {
          result.minRam_ = minRam_;
        } else {
          result.minRam_ = minRamBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Filter) {
          return mergeFrom((Filter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Filter other) {
        if (other == Filter.getDefaultInstance()) return this;
        if (other.getMaxPriceUsd() != 0D) {
          setMaxPriceUsd(other.getMaxPriceUsd());
        }
        if (other.getMinCpuCores() != 0) {
          setMinCpuCores(other.getMinCpuCores());
        }
        if (other.getMinCpuGhz() != 0D) {
          setMinCpuGhz(other.getMinCpuGhz());
        }
        if (other.hasMinRam()) {
          mergeMinRam(other.getMinRam());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Filter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Filter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double maxPriceUsd_ ;
      /**
       * <code>double max_price_usd = 1;</code>
       * @return The maxPriceUsd.
       */
      @Override
      public double getMaxPriceUsd() {
        return maxPriceUsd_;
      }
      /**
       * <code>double max_price_usd = 1;</code>
       * @param value The maxPriceUsd to set.
       * @return This builder for chaining.
       */
      public Builder setMaxPriceUsd(double value) {
        
        maxPriceUsd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double max_price_usd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxPriceUsd() {
        
        maxPriceUsd_ = 0D;
        onChanged();
        return this;
      }

      private int minCpuCores_ ;
      /**
       * <code>uint32 min_cpu_cores = 2;</code>
       * @return The minCpuCores.
       */
      @Override
      public int getMinCpuCores() {
        return minCpuCores_;
      }
      /**
       * <code>uint32 min_cpu_cores = 2;</code>
       * @param value The minCpuCores to set.
       * @return This builder for chaining.
       */
      public Builder setMinCpuCores(int value) {
        
        minCpuCores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 min_cpu_cores = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinCpuCores() {
        
        minCpuCores_ = 0;
        onChanged();
        return this;
      }

      private double minCpuGhz_ ;
      /**
       * <code>double min_cpu_ghz = 3;</code>
       * @return The minCpuGhz.
       */
      @Override
      public double getMinCpuGhz() {
        return minCpuGhz_;
      }
      /**
       * <code>double min_cpu_ghz = 3;</code>
       * @param value The minCpuGhz to set.
       * @return This builder for chaining.
       */
      public Builder setMinCpuGhz(double value) {
        
        minCpuGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double min_cpu_ghz = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinCpuGhz() {
        
        minCpuGhz_ = 0D;
        onChanged();
        return this;
      }

      private MemoryMessage.Memory minRam_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> minRamBuilder_;
      /**
       * <code>.Memory min_ram = 4;</code>
       * @return Whether the minRam field is set.
       */
      public boolean hasMinRam() {
        return minRamBuilder_ != null || minRam_ != null;
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       * @return The minRam.
       */
      public MemoryMessage.Memory getMinRam() {
        if (minRamBuilder_ == null) {
          return minRam_ == null ? MemoryMessage.Memory.getDefaultInstance() : minRam_;
        } else {
          return minRamBuilder_.getMessage();
        }
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      public Builder setMinRam(MemoryMessage.Memory value) {
        if (minRamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          minRam_ = value;
          onChanged();
        } else {
          minRamBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      public Builder setMinRam(
          MemoryMessage.Memory.Builder builderForValue) {
        if (minRamBuilder_ == null) {
          minRam_ = builderForValue.build();
          onChanged();
        } else {
          minRamBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      public Builder mergeMinRam(MemoryMessage.Memory value) {
        if (minRamBuilder_ == null) {
          if (minRam_ != null) {
            minRam_ =
              MemoryMessage.Memory.newBuilder(minRam_).mergeFrom(value).buildPartial();
          } else {
            minRam_ = value;
          }
          onChanged();
        } else {
          minRamBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      public Builder clearMinRam() {
        if (minRamBuilder_ == null) {
          minRam_ = null;
          onChanged();
        } else {
          minRam_ = null;
          minRamBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      public MemoryMessage.Memory.Builder getMinRamBuilder() {
        
        onChanged();
        return getMinRamFieldBuilder().getBuilder();
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      public MemoryMessage.MemoryOrBuilder getMinRamOrBuilder() {
        if (minRamBuilder_ != null) {
          return minRamBuilder_.getMessageOrBuilder();
        } else {
          return minRam_ == null ?
              MemoryMessage.Memory.getDefaultInstance() : minRam_;
        }
      }
      /**
       * <code>.Memory min_ram = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> 
          getMinRamFieldBuilder() {
        if (minRamBuilder_ == null) {
          minRamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder>(
                  getMinRam(),
                  getParentForChildren(),
                  isClean());
          minRam_ = null;
        }
        return minRamBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Filter)
    }

    // @@protoc_insertion_point(class_scope:Filter)
    private static final Filter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Filter();
    }

    public static Filter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Filter>
        PARSER = new com.google.protobuf.AbstractParser<Filter>() {
      @Override
      public Filter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Filter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Filter> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Filter> getParserForType() {
      return PARSER;
    }

    @Override
    public Filter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Filter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Filter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024filter_message.proto\032\024memory_message.p" +
      "roto\"e\n\006Filter\022\025\n\rmax_price_usd\030\001 \001(\001\022\025\n" +
      "\rmin_cpu_cores\030\002 \001(\r\022\023\n\013min_cpu_ghz\030\003 \001(" +
      "\001\022\030\n\007min_ram\030\004 \001(\0132\007.Memoryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MemoryMessage.getDescriptor(),
        });
    internal_static_Filter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Filter_descriptor,
        new String[] { "MaxPriceUsd", "MinCpuCores", "MinCpuGhz", "MinRam", });
    MemoryMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
