package com.implementsfun.protoj;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyboard_message.proto

public final class KeyboardMessage {
  private KeyboardMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeyboardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Keyboard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Keyboard.Layout layout = 1;</code>
     * @return The enum numeric value on the wire for layout.
     */
    int getLayoutValue();
    /**
     * <code>.Keyboard.Layout layout = 1;</code>
     * @return The layout.
     */
    Keyboard.Layout getLayout();

    /**
     * <code>bool backlit = 2;</code>
     * @return The backlit.
     */
    boolean getBacklit();
  }
  /**
   * Protobuf type {@code Keyboard}
   */
  public static final class Keyboard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Keyboard)
      KeyboardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Keyboard.newBuilder() to construct.
    private Keyboard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Keyboard() {
      layout_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Keyboard();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Keyboard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              layout_ = rawValue;
              break;
            }
            case 16: {

              backlit_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KeyboardMessage.internal_static_Keyboard_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KeyboardMessage.internal_static_Keyboard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Keyboard.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Keyboard.Layout}
     */
    public enum Layout
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>QWERTY = 1;</code>
       */
      QWERTY(1),
      /**
       * <code>QWERTZ = 2;</code>
       */
      QWERTZ(2),
      /**
       * <code>AZERTY = 3;</code>
       */
      AZERTY(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>QWERTY = 1;</code>
       */
      public static final int QWERTY_VALUE = 1;
      /**
       * <code>QWERTZ = 2;</code>
       */
      public static final int QWERTZ_VALUE = 2;
      /**
       * <code>AZERTY = 3;</code>
       */
      public static final int AZERTY_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Layout valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Layout forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return QWERTY;
          case 2: return QWERTZ;
          case 3: return AZERTY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Layout>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Layout> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Layout>() {
              public Layout findValueByNumber(int number) {
                return Layout.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Keyboard.getDescriptor().getEnumTypes().get(0);
      }

      private static final Layout[] VALUES = values();

      public static Layout valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Layout(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Keyboard.Layout)
    }

    public static final int LAYOUT_FIELD_NUMBER = 1;
    private int layout_;
    /**
     * <code>.Keyboard.Layout layout = 1;</code>
     * @return The enum numeric value on the wire for layout.
     */
    @Override public int getLayoutValue() {
      return layout_;
    }
    /**
     * <code>.Keyboard.Layout layout = 1;</code>
     * @return The layout.
     */
    @Override public Layout getLayout() {
      @SuppressWarnings("deprecation")
      Layout result = Layout.valueOf(layout_);
      return result == null ? Layout.UNRECOGNIZED : result;
    }

    public static final int BACKLIT_FIELD_NUMBER = 2;
    private boolean backlit_;
    /**
     * <code>bool backlit = 2;</code>
     * @return The backlit.
     */
    @Override
    public boolean getBacklit() {
      return backlit_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (layout_ != Layout.UNKNOWN.getNumber()) {
        output.writeEnum(1, layout_);
      }
      if (backlit_ != false) {
        output.writeBool(2, backlit_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (layout_ != Layout.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, layout_);
      }
      if (backlit_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, backlit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Keyboard)) {
        return super.equals(obj);
      }
      Keyboard other = (Keyboard) obj;

      if (layout_ != other.layout_) return false;
      if (getBacklit()
          != other.getBacklit()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LAYOUT_FIELD_NUMBER;
      hash = (53 * hash) + layout_;
      hash = (37 * hash) + BACKLIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBacklit());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Keyboard parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Keyboard parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Keyboard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Keyboard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Keyboard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Keyboard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Keyboard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Keyboard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Keyboard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Keyboard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Keyboard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Keyboard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Keyboard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Keyboard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Keyboard)
        KeyboardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KeyboardMessage.internal_static_Keyboard_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KeyboardMessage.internal_static_Keyboard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Keyboard.class, Builder.class);
      }

      // Construct using KeyboardMessage.Keyboard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        layout_ = 0;

        backlit_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KeyboardMessage.internal_static_Keyboard_descriptor;
      }

      @Override
      public Keyboard getDefaultInstanceForType() {
        return Keyboard.getDefaultInstance();
      }

      @Override
      public Keyboard build() {
        Keyboard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Keyboard buildPartial() {
        Keyboard result = new Keyboard(this);
        result.layout_ = layout_;
        result.backlit_ = backlit_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Keyboard) {
          return mergeFrom((Keyboard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Keyboard other) {
        if (other == Keyboard.getDefaultInstance()) return this;
        if (other.layout_ != 0) {
          setLayoutValue(other.getLayoutValue());
        }
        if (other.getBacklit() != false) {
          setBacklit(other.getBacklit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Keyboard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Keyboard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int layout_ = 0;
      /**
       * <code>.Keyboard.Layout layout = 1;</code>
       * @return The enum numeric value on the wire for layout.
       */
      @Override public int getLayoutValue() {
        return layout_;
      }
      /**
       * <code>.Keyboard.Layout layout = 1;</code>
       * @param value The enum numeric value on the wire for layout to set.
       * @return This builder for chaining.
       */
      public Builder setLayoutValue(int value) {
        
        layout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Keyboard.Layout layout = 1;</code>
       * @return The layout.
       */
      @Override
      public Layout getLayout() {
        @SuppressWarnings("deprecation")
        Layout result = Layout.valueOf(layout_);
        return result == null ? Layout.UNRECOGNIZED : result;
      }
      /**
       * <code>.Keyboard.Layout layout = 1;</code>
       * @param value The layout to set.
       * @return This builder for chaining.
       */
      public Builder setLayout(Layout value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        layout_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Keyboard.Layout layout = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLayout() {
        
        layout_ = 0;
        onChanged();
        return this;
      }

      private boolean backlit_ ;
      /**
       * <code>bool backlit = 2;</code>
       * @return The backlit.
       */
      @Override
      public boolean getBacklit() {
        return backlit_;
      }
      /**
       * <code>bool backlit = 2;</code>
       * @param value The backlit to set.
       * @return This builder for chaining.
       */
      public Builder setBacklit(boolean value) {
        
        backlit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool backlit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBacklit() {
        
        backlit_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Keyboard)
    }

    // @@protoc_insertion_point(class_scope:Keyboard)
    private static final Keyboard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Keyboard();
    }

    public static Keyboard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Keyboard>
        PARSER = new com.google.protobuf.AbstractParser<Keyboard>() {
      @Override
      public Keyboard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Keyboard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Keyboard> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Keyboard> getParserForType() {
      return PARSER;
    }

    @Override
    public Keyboard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Keyboard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Keyboard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026keyboard_message.proto\"x\n\010Keyboard\022 \n\006" +
      "layout\030\001 \001(\0162\020.Keyboard.Layout\022\017\n\007backli" +
      "t\030\002 \001(\010\"9\n\006Layout\022\013\n\007UNKNOWN\020\000\022\n\n\006QWERTY" +
      "\020\001\022\n\n\006QWERTZ\020\002\022\n\n\006AZERTY\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Keyboard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Keyboard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Keyboard_descriptor,
        new String[] { "Layout", "Backlit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
