package com.implementsfun.protoj;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop_message.proto

public final class LaptopMessage {
  private LaptopMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LaptopOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Laptop)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string brand = 2;</code>
     * @return The brand.
     */
    String getBrand();
    /**
     * <code>string brand = 2;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.CPU cpu = 4;</code>
     * @return Whether the cpu field is set.
     */
    boolean hasCpu();
    /**
     * <code>.CPU cpu = 4;</code>
     * @return The cpu.
     */
    ProcessorMessage.CPU getCpu();
    /**
     * <code>.CPU cpu = 4;</code>
     */
    ProcessorMessage.CPUOrBuilder getCpuOrBuilder();

    /**
     * <code>.Memory ram = 5;</code>
     * @return Whether the ram field is set.
     */
    boolean hasRam();
    /**
     * <code>.Memory ram = 5;</code>
     * @return The ram.
     */
    MemoryMessage.Memory getRam();
    /**
     * <code>.Memory ram = 5;</code>
     */
    MemoryMessage.MemoryOrBuilder getRamOrBuilder();

    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    java.util.List<ProcessorMessage.GPU> 
        getGpusList();
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    ProcessorMessage.GPU getGpus(int index);
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    int getGpusCount();
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    java.util.List<? extends ProcessorMessage.GPUOrBuilder> 
        getGpusOrBuilderList();
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    ProcessorMessage.GPUOrBuilder getGpusOrBuilder(
        int index);

    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    java.util.List<StorageMessage.Storage> 
        getStoragesList();
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    StorageMessage.Storage getStorages(int index);
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    int getStoragesCount();
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    java.util.List<? extends StorageMessage.StorageOrBuilder> 
        getStoragesOrBuilderList();
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    StorageMessage.StorageOrBuilder getStoragesOrBuilder(
        int index);

    /**
     * <code>.Screen screen = 8;</code>
     * @return Whether the screen field is set.
     */
    boolean hasScreen();
    /**
     * <code>.Screen screen = 8;</code>
     * @return The screen.
     */
    ScreenMessage.Screen getScreen();
    /**
     * <code>.Screen screen = 8;</code>
     */
    ScreenMessage.ScreenOrBuilder getScreenOrBuilder();

    /**
     * <code>.Keyboard keyboard = 9;</code>
     * @return Whether the keyboard field is set.
     */
    boolean hasKeyboard();
    /**
     * <code>.Keyboard keyboard = 9;</code>
     * @return The keyboard.
     */
    KeyboardMessage.Keyboard getKeyboard();
    /**
     * <code>.Keyboard keyboard = 9;</code>
     */
    KeyboardMessage.KeyboardOrBuilder getKeyboardOrBuilder();

    /**
     * <code>double weight_kg = 10;</code>
     * @return Whether the weightKg field is set.
     */
    boolean hasWeightKg();
    /**
     * <code>double weight_kg = 10;</code>
     * @return The weightKg.
     */
    double getWeightKg();

    /**
     * <code>double weight_lb = 11;</code>
     * @return Whether the weightLb field is set.
     */
    boolean hasWeightLb();
    /**
     * <code>double weight_lb = 11;</code>
     * @return The weightLb.
     */
    double getWeightLb();

    /**
     * <code>double price_usd = 12;</code>
     * @return The priceUsd.
     */
    double getPriceUsd();

    /**
     * <code>uint32 release_year = 13;</code>
     * @return The releaseYear.
     */
    int getReleaseYear();

    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     * @return The updatedAt.
     */
    com.google.protobuf.Timestamp getUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

    public Laptop.WeightCase getWeightCase();
  }
  /**
   * Protobuf type {@code Laptop}
   */
  public static final class Laptop extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Laptop)
      LaptopOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Laptop.newBuilder() to construct.
    private Laptop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Laptop() {
      id_ = "";
      brand_ = "";
      name_ = "";
      gpus_ = java.util.Collections.emptyList();
      storages_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Laptop();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Laptop(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              ProcessorMessage.CPU.Builder subBuilder = null;
              if (cpu_ != null) {
                subBuilder = cpu_.toBuilder();
              }
              cpu_ = input.readMessage(ProcessorMessage.CPU.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cpu_);
                cpu_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              MemoryMessage.Memory.Builder subBuilder = null;
              if (ram_ != null) {
                subBuilder = ram_.toBuilder();
              }
              ram_ = input.readMessage(MemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ram_);
                ram_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gpus_ = new java.util.ArrayList<ProcessorMessage.GPU>();
                mutable_bitField0_ |= 0x00000001;
              }
              gpus_.add(
                  input.readMessage(ProcessorMessage.GPU.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                storages_ = new java.util.ArrayList<StorageMessage.Storage>();
                mutable_bitField0_ |= 0x00000002;
              }
              storages_.add(
                  input.readMessage(StorageMessage.Storage.parser(), extensionRegistry));
              break;
            }
            case 66: {
              ScreenMessage.Screen.Builder subBuilder = null;
              if (screen_ != null) {
                subBuilder = screen_.toBuilder();
              }
              screen_ = input.readMessage(ScreenMessage.Screen.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(screen_);
                screen_ = subBuilder.buildPartial();
              }

              break;
            }
            case 74: {
              KeyboardMessage.Keyboard.Builder subBuilder = null;
              if (keyboard_ != null) {
                subBuilder = keyboard_.toBuilder();
              }
              keyboard_ = input.readMessage(KeyboardMessage.Keyboard.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(keyboard_);
                keyboard_ = subBuilder.buildPartial();
              }

              break;
            }
            case 81: {
              weight_ = input.readDouble();
              weightCase_ = 10;
              break;
            }
            case 89: {
              weight_ = input.readDouble();
              weightCase_ = 11;
              break;
            }
            case 97: {

              priceUsd_ = input.readDouble();
              break;
            }
            case 104: {

              releaseYear_ = input.readUInt32();
              break;
            }
            case 114: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updatedAt_ != null) {
                subBuilder = updatedAt_.toBuilder();
              }
              updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updatedAt_);
                updatedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gpus_ = java.util.Collections.unmodifiableList(gpus_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          storages_ = java.util.Collections.unmodifiableList(storages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LaptopMessage.internal_static_Laptop_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LaptopMessage.internal_static_Laptop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Laptop.class, Builder.class);
    }

    private int weightCase_ = 0;
    private Object weight_;
    public enum WeightCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      WEIGHT_KG(10),
      WEIGHT_LB(11),
      WEIGHT_NOT_SET(0);
      private final int value;
      private WeightCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static WeightCase valueOf(int value) {
        return forNumber(value);
      }

      public static WeightCase forNumber(int value) {
        switch (value) {
          case 10: return WEIGHT_KG;
          case 11: return WEIGHT_LB;
          case 0: return WEIGHT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public WeightCase
    getWeightCase() {
      return WeightCase.forNumber(
          weightCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 2;
    private volatile Object brand_;
    /**
     * <code>string brand = 2;</code>
     * @return The brand.
     */
    @Override
    public String getBrand() {
      Object ref = brand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 2;</code>
     * @return The bytes for brand.
     */
    @Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_FIELD_NUMBER = 4;
    private ProcessorMessage.CPU cpu_;
    /**
     * <code>.CPU cpu = 4;</code>
     * @return Whether the cpu field is set.
     */
    @Override
    public boolean hasCpu() {
      return cpu_ != null;
    }
    /**
     * <code>.CPU cpu = 4;</code>
     * @return The cpu.
     */
    @Override
    public ProcessorMessage.CPU getCpu() {
      return cpu_ == null ? ProcessorMessage.CPU.getDefaultInstance() : cpu_;
    }
    /**
     * <code>.CPU cpu = 4;</code>
     */
    @Override
    public ProcessorMessage.CPUOrBuilder getCpuOrBuilder() {
      return getCpu();
    }

    public static final int RAM_FIELD_NUMBER = 5;
    private MemoryMessage.Memory ram_;
    /**
     * <code>.Memory ram = 5;</code>
     * @return Whether the ram field is set.
     */
    @Override
    public boolean hasRam() {
      return ram_ != null;
    }
    /**
     * <code>.Memory ram = 5;</code>
     * @return The ram.
     */
    @Override
    public MemoryMessage.Memory getRam() {
      return ram_ == null ? MemoryMessage.Memory.getDefaultInstance() : ram_;
    }
    /**
     * <code>.Memory ram = 5;</code>
     */
    @Override
    public MemoryMessage.MemoryOrBuilder getRamOrBuilder() {
      return getRam();
    }

    public static final int GPUS_FIELD_NUMBER = 6;
    private java.util.List<ProcessorMessage.GPU> gpus_;
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    @Override
    public java.util.List<ProcessorMessage.GPU> getGpusList() {
      return gpus_;
    }
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    @Override
    public java.util.List<? extends ProcessorMessage.GPUOrBuilder> 
        getGpusOrBuilderList() {
      return gpus_;
    }
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    @Override
    public int getGpusCount() {
      return gpus_.size();
    }
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    @Override
    public ProcessorMessage.GPU getGpus(int index) {
      return gpus_.get(index);
    }
    /**
     * <code>repeated .GPU gpus = 6;</code>
     */
    @Override
    public ProcessorMessage.GPUOrBuilder getGpusOrBuilder(
        int index) {
      return gpus_.get(index);
    }

    public static final int STORAGES_FIELD_NUMBER = 7;
    private java.util.List<StorageMessage.Storage> storages_;
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    @Override
    public java.util.List<StorageMessage.Storage> getStoragesList() {
      return storages_;
    }
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    @Override
    public java.util.List<? extends StorageMessage.StorageOrBuilder> 
        getStoragesOrBuilderList() {
      return storages_;
    }
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    @Override
    public int getStoragesCount() {
      return storages_.size();
    }
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    @Override
    public StorageMessage.Storage getStorages(int index) {
      return storages_.get(index);
    }
    /**
     * <code>repeated .Storage storages = 7;</code>
     */
    @Override
    public StorageMessage.StorageOrBuilder getStoragesOrBuilder(
        int index) {
      return storages_.get(index);
    }

    public static final int SCREEN_FIELD_NUMBER = 8;
    private ScreenMessage.Screen screen_;
    /**
     * <code>.Screen screen = 8;</code>
     * @return Whether the screen field is set.
     */
    @Override
    public boolean hasScreen() {
      return screen_ != null;
    }
    /**
     * <code>.Screen screen = 8;</code>
     * @return The screen.
     */
    @Override
    public ScreenMessage.Screen getScreen() {
      return screen_ == null ? ScreenMessage.Screen.getDefaultInstance() : screen_;
    }
    /**
     * <code>.Screen screen = 8;</code>
     */
    @Override
    public ScreenMessage.ScreenOrBuilder getScreenOrBuilder() {
      return getScreen();
    }

    public static final int KEYBOARD_FIELD_NUMBER = 9;
    private KeyboardMessage.Keyboard keyboard_;
    /**
     * <code>.Keyboard keyboard = 9;</code>
     * @return Whether the keyboard field is set.
     */
    @Override
    public boolean hasKeyboard() {
      return keyboard_ != null;
    }
    /**
     * <code>.Keyboard keyboard = 9;</code>
     * @return The keyboard.
     */
    @Override
    public KeyboardMessage.Keyboard getKeyboard() {
      return keyboard_ == null ? KeyboardMessage.Keyboard.getDefaultInstance() : keyboard_;
    }
    /**
     * <code>.Keyboard keyboard = 9;</code>
     */
    @Override
    public KeyboardMessage.KeyboardOrBuilder getKeyboardOrBuilder() {
      return getKeyboard();
    }

    public static final int WEIGHT_KG_FIELD_NUMBER = 10;
    /**
     * <code>double weight_kg = 10;</code>
     * @return Whether the weightKg field is set.
     */
    @Override
    public boolean hasWeightKg() {
      return weightCase_ == 10;
    }
    /**
     * <code>double weight_kg = 10;</code>
     * @return The weightKg.
     */
    @Override
    public double getWeightKg() {
      if (weightCase_ == 10) {
        return (Double) weight_;
      }
      return 0D;
    }

    public static final int WEIGHT_LB_FIELD_NUMBER = 11;
    /**
     * <code>double weight_lb = 11;</code>
     * @return Whether the weightLb field is set.
     */
    @Override
    public boolean hasWeightLb() {
      return weightCase_ == 11;
    }
    /**
     * <code>double weight_lb = 11;</code>
     * @return The weightLb.
     */
    @Override
    public double getWeightLb() {
      if (weightCase_ == 11) {
        return (Double) weight_;
      }
      return 0D;
    }

    public static final int PRICE_USD_FIELD_NUMBER = 12;
    private double priceUsd_;
    /**
     * <code>double price_usd = 12;</code>
     * @return The priceUsd.
     */
    @Override
    public double getPriceUsd() {
      return priceUsd_;
    }

    public static final int RELEASE_YEAR_FIELD_NUMBER = 13;
    private int releaseYear_;
    /**
     * <code>uint32 release_year = 13;</code>
     * @return The releaseYear.
     */
    @Override
    public int getReleaseYear() {
      return releaseYear_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 14;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     * @return Whether the updatedAt field is set.
     */
    @Override
    public boolean hasUpdatedAt() {
      return updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     * @return The updatedAt.
     */
    @Override
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      return getUpdatedAt();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (cpu_ != null) {
        output.writeMessage(4, getCpu());
      }
      if (ram_ != null) {
        output.writeMessage(5, getRam());
      }
      for (int i = 0; i < gpus_.size(); i++) {
        output.writeMessage(6, gpus_.get(i));
      }
      for (int i = 0; i < storages_.size(); i++) {
        output.writeMessage(7, storages_.get(i));
      }
      if (screen_ != null) {
        output.writeMessage(8, getScreen());
      }
      if (keyboard_ != null) {
        output.writeMessage(9, getKeyboard());
      }
      if (weightCase_ == 10) {
        output.writeDouble(
            10, (double)((Double) weight_));
      }
      if (weightCase_ == 11) {
        output.writeDouble(
            11, (double)((Double) weight_));
      }
      if (Double.doubleToRawLongBits(priceUsd_) != 0) {
        output.writeDouble(12, priceUsd_);
      }
      if (releaseYear_ != 0) {
        output.writeUInt32(13, releaseYear_);
      }
      if (updatedAt_ != null) {
        output.writeMessage(14, getUpdatedAt());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (cpu_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCpu());
      }
      if (ram_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRam());
      }
      for (int i = 0; i < gpus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, gpus_.get(i));
      }
      for (int i = 0; i < storages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, storages_.get(i));
      }
      if (screen_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getScreen());
      }
      if (keyboard_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getKeyboard());
      }
      if (weightCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              10, (double)((Double) weight_));
      }
      if (weightCase_ == 11) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              11, (double)((Double) weight_));
      }
      if (Double.doubleToRawLongBits(priceUsd_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, priceUsd_);
      }
      if (releaseYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, releaseYear_);
      }
      if (updatedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getUpdatedAt());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Laptop)) {
        return super.equals(obj);
      }
      Laptop other = (Laptop) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasCpu() != other.hasCpu()) return false;
      if (hasCpu()) {
        if (!getCpu()
            .equals(other.getCpu())) return false;
      }
      if (hasRam() != other.hasRam()) return false;
      if (hasRam()) {
        if (!getRam()
            .equals(other.getRam())) return false;
      }
      if (!getGpusList()
          .equals(other.getGpusList())) return false;
      if (!getStoragesList()
          .equals(other.getStoragesList())) return false;
      if (hasScreen() != other.hasScreen()) return false;
      if (hasScreen()) {
        if (!getScreen()
            .equals(other.getScreen())) return false;
      }
      if (hasKeyboard() != other.hasKeyboard()) return false;
      if (hasKeyboard()) {
        if (!getKeyboard()
            .equals(other.getKeyboard())) return false;
      }
      if (Double.doubleToLongBits(getPriceUsd())
          != Double.doubleToLongBits(
              other.getPriceUsd())) return false;
      if (getReleaseYear()
          != other.getReleaseYear()) return false;
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (!getWeightCase().equals(other.getWeightCase())) return false;
      switch (weightCase_) {
        case 10:
          if (Double.doubleToLongBits(getWeightKg())
              != Double.doubleToLongBits(
                  other.getWeightKg())) return false;
          break;
        case 11:
          if (Double.doubleToLongBits(getWeightLb())
              != Double.doubleToLongBits(
                  other.getWeightLb())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasCpu()) {
        hash = (37 * hash) + CPU_FIELD_NUMBER;
        hash = (53 * hash) + getCpu().hashCode();
      }
      if (hasRam()) {
        hash = (37 * hash) + RAM_FIELD_NUMBER;
        hash = (53 * hash) + getRam().hashCode();
      }
      if (getGpusCount() > 0) {
        hash = (37 * hash) + GPUS_FIELD_NUMBER;
        hash = (53 * hash) + getGpusList().hashCode();
      }
      if (getStoragesCount() > 0) {
        hash = (37 * hash) + STORAGES_FIELD_NUMBER;
        hash = (53 * hash) + getStoragesList().hashCode();
      }
      if (hasScreen()) {
        hash = (37 * hash) + SCREEN_FIELD_NUMBER;
        hash = (53 * hash) + getScreen().hashCode();
      }
      if (hasKeyboard()) {
        hash = (37 * hash) + KEYBOARD_FIELD_NUMBER;
        hash = (53 * hash) + getKeyboard().hashCode();
      }
      hash = (37 * hash) + PRICE_USD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getPriceUsd()));
      hash = (37 * hash) + RELEASE_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseYear();
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      switch (weightCase_) {
        case 10:
          hash = (37 * hash) + WEIGHT_KG_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getWeightKg()));
          break;
        case 11:
          hash = (37 * hash) + WEIGHT_LB_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getWeightLb()));
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Laptop parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Laptop parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Laptop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Laptop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Laptop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Laptop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Laptop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Laptop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Laptop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Laptop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Laptop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Laptop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Laptop prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Laptop}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Laptop)
        LaptopOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LaptopMessage.internal_static_Laptop_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LaptopMessage.internal_static_Laptop_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Laptop.class, Builder.class);
      }

      // Construct using LaptopMessage.Laptop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGpusFieldBuilder();
          getStoragesFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        brand_ = "";

        name_ = "";

        if (cpuBuilder_ == null) {
          cpu_ = null;
        } else {
          cpu_ = null;
          cpuBuilder_ = null;
        }
        if (ramBuilder_ == null) {
          ram_ = null;
        } else {
          ram_ = null;
          ramBuilder_ = null;
        }
        if (gpusBuilder_ == null) {
          gpus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gpusBuilder_.clear();
        }
        if (storagesBuilder_ == null) {
          storages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          storagesBuilder_.clear();
        }
        if (screenBuilder_ == null) {
          screen_ = null;
        } else {
          screen_ = null;
          screenBuilder_ = null;
        }
        if (keyboardBuilder_ == null) {
          keyboard_ = null;
        } else {
          keyboard_ = null;
          keyboardBuilder_ = null;
        }
        priceUsd_ = 0D;

        releaseYear_ = 0;

        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }
        weightCase_ = 0;
        weight_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LaptopMessage.internal_static_Laptop_descriptor;
      }

      @Override
      public Laptop getDefaultInstanceForType() {
        return Laptop.getDefaultInstance();
      }

      @Override
      public Laptop build() {
        Laptop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Laptop buildPartial() {
        Laptop result = new Laptop(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.brand_ = brand_;
        result.name_ = name_;
        if (cpuBuilder_ == null) {
          result.cpu_ = cpu_;
        } else {
          result.cpu_ = cpuBuilder_.build();
        }
        if (ramBuilder_ == null) {
          result.ram_ = ram_;
        } else {
          result.ram_ = ramBuilder_.build();
        }
        if (gpusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gpus_ = java.util.Collections.unmodifiableList(gpus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gpus_ = gpus_;
        } else {
          result.gpus_ = gpusBuilder_.build();
        }
        if (storagesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            storages_ = java.util.Collections.unmodifiableList(storages_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.storages_ = storages_;
        } else {
          result.storages_ = storagesBuilder_.build();
        }
        if (screenBuilder_ == null) {
          result.screen_ = screen_;
        } else {
          result.screen_ = screenBuilder_.build();
        }
        if (keyboardBuilder_ == null) {
          result.keyboard_ = keyboard_;
        } else {
          result.keyboard_ = keyboardBuilder_.build();
        }
        if (weightCase_ == 10) {
          result.weight_ = weight_;
        }
        if (weightCase_ == 11) {
          result.weight_ = weight_;
        }
        result.priceUsd_ = priceUsd_;
        result.releaseYear_ = releaseYear_;
        if (updatedAtBuilder_ == null) {
          result.updatedAt_ = updatedAt_;
        } else {
          result.updatedAt_ = updatedAtBuilder_.build();
        }
        result.weightCase_ = weightCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Laptop) {
          return mergeFrom((Laptop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Laptop other) {
        if (other == Laptop.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCpu()) {
          mergeCpu(other.getCpu());
        }
        if (other.hasRam()) {
          mergeRam(other.getRam());
        }
        if (gpusBuilder_ == null) {
          if (!other.gpus_.isEmpty()) {
            if (gpus_.isEmpty()) {
              gpus_ = other.gpus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGpusIsMutable();
              gpus_.addAll(other.gpus_);
            }
            onChanged();
          }
        } else {
          if (!other.gpus_.isEmpty()) {
            if (gpusBuilder_.isEmpty()) {
              gpusBuilder_.dispose();
              gpusBuilder_ = null;
              gpus_ = other.gpus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gpusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGpusFieldBuilder() : null;
            } else {
              gpusBuilder_.addAllMessages(other.gpus_);
            }
          }
        }
        if (storagesBuilder_ == null) {
          if (!other.storages_.isEmpty()) {
            if (storages_.isEmpty()) {
              storages_ = other.storages_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStoragesIsMutable();
              storages_.addAll(other.storages_);
            }
            onChanged();
          }
        } else {
          if (!other.storages_.isEmpty()) {
            if (storagesBuilder_.isEmpty()) {
              storagesBuilder_.dispose();
              storagesBuilder_ = null;
              storages_ = other.storages_;
              bitField0_ = (bitField0_ & ~0x00000002);
              storagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStoragesFieldBuilder() : null;
            } else {
              storagesBuilder_.addAllMessages(other.storages_);
            }
          }
        }
        if (other.hasScreen()) {
          mergeScreen(other.getScreen());
        }
        if (other.hasKeyboard()) {
          mergeKeyboard(other.getKeyboard());
        }
        if (other.getPriceUsd() != 0D) {
          setPriceUsd(other.getPriceUsd());
        }
        if (other.getReleaseYear() != 0) {
          setReleaseYear(other.getReleaseYear());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        switch (other.getWeightCase()) {
          case WEIGHT_KG: {
            setWeightKg(other.getWeightKg());
            break;
          }
          case WEIGHT_LB: {
            setWeightLb(other.getWeightLb());
            break;
          }
          case WEIGHT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Laptop parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Laptop) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int weightCase_ = 0;
      private Object weight_;
      public WeightCase
          getWeightCase() {
        return WeightCase.forNumber(
            weightCase_);
      }

      public Builder clearWeight() {
        weightCase_ = 0;
        weight_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object brand_ = "";
      /**
       * <code>string brand = 2;</code>
       * @return The brand.
       */
      public String getBrand() {
        Object ref = brand_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string brand = 2;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 2;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 2;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private ProcessorMessage.CPU cpu_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProcessorMessage.CPU, ProcessorMessage.CPU.Builder, ProcessorMessage.CPUOrBuilder> cpuBuilder_;
      /**
       * <code>.CPU cpu = 4;</code>
       * @return Whether the cpu field is set.
       */
      public boolean hasCpu() {
        return cpuBuilder_ != null || cpu_ != null;
      }
      /**
       * <code>.CPU cpu = 4;</code>
       * @return The cpu.
       */
      public ProcessorMessage.CPU getCpu() {
        if (cpuBuilder_ == null) {
          return cpu_ == null ? ProcessorMessage.CPU.getDefaultInstance() : cpu_;
        } else {
          return cpuBuilder_.getMessage();
        }
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      public Builder setCpu(ProcessorMessage.CPU value) {
        if (cpuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cpu_ = value;
          onChanged();
        } else {
          cpuBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      public Builder setCpu(
          ProcessorMessage.CPU.Builder builderForValue) {
        if (cpuBuilder_ == null) {
          cpu_ = builderForValue.build();
          onChanged();
        } else {
          cpuBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      public Builder mergeCpu(ProcessorMessage.CPU value) {
        if (cpuBuilder_ == null) {
          if (cpu_ != null) {
            cpu_ =
              ProcessorMessage.CPU.newBuilder(cpu_).mergeFrom(value).buildPartial();
          } else {
            cpu_ = value;
          }
          onChanged();
        } else {
          cpuBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      public Builder clearCpu() {
        if (cpuBuilder_ == null) {
          cpu_ = null;
          onChanged();
        } else {
          cpu_ = null;
          cpuBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      public ProcessorMessage.CPU.Builder getCpuBuilder() {
        
        onChanged();
        return getCpuFieldBuilder().getBuilder();
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      public ProcessorMessage.CPUOrBuilder getCpuOrBuilder() {
        if (cpuBuilder_ != null) {
          return cpuBuilder_.getMessageOrBuilder();
        } else {
          return cpu_ == null ?
              ProcessorMessage.CPU.getDefaultInstance() : cpu_;
        }
      }
      /**
       * <code>.CPU cpu = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProcessorMessage.CPU, ProcessorMessage.CPU.Builder, ProcessorMessage.CPUOrBuilder> 
          getCpuFieldBuilder() {
        if (cpuBuilder_ == null) {
          cpuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProcessorMessage.CPU, ProcessorMessage.CPU.Builder, ProcessorMessage.CPUOrBuilder>(
                  getCpu(),
                  getParentForChildren(),
                  isClean());
          cpu_ = null;
        }
        return cpuBuilder_;
      }

      private MemoryMessage.Memory ram_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> ramBuilder_;
      /**
       * <code>.Memory ram = 5;</code>
       * @return Whether the ram field is set.
       */
      public boolean hasRam() {
        return ramBuilder_ != null || ram_ != null;
      }
      /**
       * <code>.Memory ram = 5;</code>
       * @return The ram.
       */
      public MemoryMessage.Memory getRam() {
        if (ramBuilder_ == null) {
          return ram_ == null ? MemoryMessage.Memory.getDefaultInstance() : ram_;
        } else {
          return ramBuilder_.getMessage();
        }
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      public Builder setRam(MemoryMessage.Memory value) {
        if (ramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ram_ = value;
          onChanged();
        } else {
          ramBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      public Builder setRam(
          MemoryMessage.Memory.Builder builderForValue) {
        if (ramBuilder_ == null) {
          ram_ = builderForValue.build();
          onChanged();
        } else {
          ramBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      public Builder mergeRam(MemoryMessage.Memory value) {
        if (ramBuilder_ == null) {
          if (ram_ != null) {
            ram_ =
              MemoryMessage.Memory.newBuilder(ram_).mergeFrom(value).buildPartial();
          } else {
            ram_ = value;
          }
          onChanged();
        } else {
          ramBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      public Builder clearRam() {
        if (ramBuilder_ == null) {
          ram_ = null;
          onChanged();
        } else {
          ram_ = null;
          ramBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      public MemoryMessage.Memory.Builder getRamBuilder() {
        
        onChanged();
        return getRamFieldBuilder().getBuilder();
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      public MemoryMessage.MemoryOrBuilder getRamOrBuilder() {
        if (ramBuilder_ != null) {
          return ramBuilder_.getMessageOrBuilder();
        } else {
          return ram_ == null ?
              MemoryMessage.Memory.getDefaultInstance() : ram_;
        }
      }
      /**
       * <code>.Memory ram = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> 
          getRamFieldBuilder() {
        if (ramBuilder_ == null) {
          ramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder>(
                  getRam(),
                  getParentForChildren(),
                  isClean());
          ram_ = null;
        }
        return ramBuilder_;
      }

      private java.util.List<ProcessorMessage.GPU> gpus_ =
        java.util.Collections.emptyList();
      private void ensureGpusIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gpus_ = new java.util.ArrayList<ProcessorMessage.GPU>(gpus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProcessorMessage.GPU, ProcessorMessage.GPU.Builder, ProcessorMessage.GPUOrBuilder> gpusBuilder_;

      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public java.util.List<ProcessorMessage.GPU> getGpusList() {
        if (gpusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gpus_);
        } else {
          return gpusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public int getGpusCount() {
        if (gpusBuilder_ == null) {
          return gpus_.size();
        } else {
          return gpusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public ProcessorMessage.GPU getGpus(int index) {
        if (gpusBuilder_ == null) {
          return gpus_.get(index);
        } else {
          return gpusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder setGpus(
          int index, ProcessorMessage.GPU value) {
        if (gpusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpusIsMutable();
          gpus_.set(index, value);
          onChanged();
        } else {
          gpusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder setGpus(
          int index, ProcessorMessage.GPU.Builder builderForValue) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.set(index, builderForValue.build());
          onChanged();
        } else {
          gpusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder addGpus(ProcessorMessage.GPU value) {
        if (gpusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpusIsMutable();
          gpus_.add(value);
          onChanged();
        } else {
          gpusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder addGpus(
          int index, ProcessorMessage.GPU value) {
        if (gpusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpusIsMutable();
          gpus_.add(index, value);
          onChanged();
        } else {
          gpusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder addGpus(
          ProcessorMessage.GPU.Builder builderForValue) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.add(builderForValue.build());
          onChanged();
        } else {
          gpusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder addGpus(
          int index, ProcessorMessage.GPU.Builder builderForValue) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.add(index, builderForValue.build());
          onChanged();
        } else {
          gpusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder addAllGpus(
          Iterable<? extends ProcessorMessage.GPU> values) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gpus_);
          onChanged();
        } else {
          gpusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder clearGpus() {
        if (gpusBuilder_ == null) {
          gpus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gpusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public Builder removeGpus(int index) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.remove(index);
          onChanged();
        } else {
          gpusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public ProcessorMessage.GPU.Builder getGpusBuilder(
          int index) {
        return getGpusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public ProcessorMessage.GPUOrBuilder getGpusOrBuilder(
          int index) {
        if (gpusBuilder_ == null) {
          return gpus_.get(index);  } else {
          return gpusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public java.util.List<? extends ProcessorMessage.GPUOrBuilder> 
           getGpusOrBuilderList() {
        if (gpusBuilder_ != null) {
          return gpusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gpus_);
        }
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public ProcessorMessage.GPU.Builder addGpusBuilder() {
        return getGpusFieldBuilder().addBuilder(
            ProcessorMessage.GPU.getDefaultInstance());
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public ProcessorMessage.GPU.Builder addGpusBuilder(
          int index) {
        return getGpusFieldBuilder().addBuilder(
            index, ProcessorMessage.GPU.getDefaultInstance());
      }
      /**
       * <code>repeated .GPU gpus = 6;</code>
       */
      public java.util.List<ProcessorMessage.GPU.Builder> 
           getGpusBuilderList() {
        return getGpusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProcessorMessage.GPU, ProcessorMessage.GPU.Builder, ProcessorMessage.GPUOrBuilder> 
          getGpusFieldBuilder() {
        if (gpusBuilder_ == null) {
          gpusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProcessorMessage.GPU, ProcessorMessage.GPU.Builder, ProcessorMessage.GPUOrBuilder>(
                  gpus_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gpus_ = null;
        }
        return gpusBuilder_;
      }

      private java.util.List<StorageMessage.Storage> storages_ =
        java.util.Collections.emptyList();
      private void ensureStoragesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          storages_ = new java.util.ArrayList<StorageMessage.Storage>(storages_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          StorageMessage.Storage, StorageMessage.Storage.Builder, StorageMessage.StorageOrBuilder> storagesBuilder_;

      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public java.util.List<StorageMessage.Storage> getStoragesList() {
        if (storagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(storages_);
        } else {
          return storagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public int getStoragesCount() {
        if (storagesBuilder_ == null) {
          return storages_.size();
        } else {
          return storagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public StorageMessage.Storage getStorages(int index) {
        if (storagesBuilder_ == null) {
          return storages_.get(index);
        } else {
          return storagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder setStorages(
          int index, StorageMessage.Storage value) {
        if (storagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStoragesIsMutable();
          storages_.set(index, value);
          onChanged();
        } else {
          storagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder setStorages(
          int index, StorageMessage.Storage.Builder builderForValue) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.set(index, builderForValue.build());
          onChanged();
        } else {
          storagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder addStorages(StorageMessage.Storage value) {
        if (storagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStoragesIsMutable();
          storages_.add(value);
          onChanged();
        } else {
          storagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder addStorages(
          int index, StorageMessage.Storage value) {
        if (storagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStoragesIsMutable();
          storages_.add(index, value);
          onChanged();
        } else {
          storagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder addStorages(
          StorageMessage.Storage.Builder builderForValue) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.add(builderForValue.build());
          onChanged();
        } else {
          storagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder addStorages(
          int index, StorageMessage.Storage.Builder builderForValue) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.add(index, builderForValue.build());
          onChanged();
        } else {
          storagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder addAllStorages(
          Iterable<? extends StorageMessage.Storage> values) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, storages_);
          onChanged();
        } else {
          storagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder clearStorages() {
        if (storagesBuilder_ == null) {
          storages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          storagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public Builder removeStorages(int index) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.remove(index);
          onChanged();
        } else {
          storagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public StorageMessage.Storage.Builder getStoragesBuilder(
          int index) {
        return getStoragesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public StorageMessage.StorageOrBuilder getStoragesOrBuilder(
          int index) {
        if (storagesBuilder_ == null) {
          return storages_.get(index);  } else {
          return storagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public java.util.List<? extends StorageMessage.StorageOrBuilder> 
           getStoragesOrBuilderList() {
        if (storagesBuilder_ != null) {
          return storagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(storages_);
        }
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public StorageMessage.Storage.Builder addStoragesBuilder() {
        return getStoragesFieldBuilder().addBuilder(
            StorageMessage.Storage.getDefaultInstance());
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public StorageMessage.Storage.Builder addStoragesBuilder(
          int index) {
        return getStoragesFieldBuilder().addBuilder(
            index, StorageMessage.Storage.getDefaultInstance());
      }
      /**
       * <code>repeated .Storage storages = 7;</code>
       */
      public java.util.List<StorageMessage.Storage.Builder> 
           getStoragesBuilderList() {
        return getStoragesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          StorageMessage.Storage, StorageMessage.Storage.Builder, StorageMessage.StorageOrBuilder> 
          getStoragesFieldBuilder() {
        if (storagesBuilder_ == null) {
          storagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              StorageMessage.Storage, StorageMessage.Storage.Builder, StorageMessage.StorageOrBuilder>(
                  storages_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          storages_ = null;
        }
        return storagesBuilder_;
      }

      private ScreenMessage.Screen screen_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ScreenMessage.Screen, ScreenMessage.Screen.Builder, ScreenMessage.ScreenOrBuilder> screenBuilder_;
      /**
       * <code>.Screen screen = 8;</code>
       * @return Whether the screen field is set.
       */
      public boolean hasScreen() {
        return screenBuilder_ != null || screen_ != null;
      }
      /**
       * <code>.Screen screen = 8;</code>
       * @return The screen.
       */
      public ScreenMessage.Screen getScreen() {
        if (screenBuilder_ == null) {
          return screen_ == null ? ScreenMessage.Screen.getDefaultInstance() : screen_;
        } else {
          return screenBuilder_.getMessage();
        }
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      public Builder setScreen(ScreenMessage.Screen value) {
        if (screenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          screen_ = value;
          onChanged();
        } else {
          screenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      public Builder setScreen(
          ScreenMessage.Screen.Builder builderForValue) {
        if (screenBuilder_ == null) {
          screen_ = builderForValue.build();
          onChanged();
        } else {
          screenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      public Builder mergeScreen(ScreenMessage.Screen value) {
        if (screenBuilder_ == null) {
          if (screen_ != null) {
            screen_ =
              ScreenMessage.Screen.newBuilder(screen_).mergeFrom(value).buildPartial();
          } else {
            screen_ = value;
          }
          onChanged();
        } else {
          screenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      public Builder clearScreen() {
        if (screenBuilder_ == null) {
          screen_ = null;
          onChanged();
        } else {
          screen_ = null;
          screenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      public ScreenMessage.Screen.Builder getScreenBuilder() {
        
        onChanged();
        return getScreenFieldBuilder().getBuilder();
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      public ScreenMessage.ScreenOrBuilder getScreenOrBuilder() {
        if (screenBuilder_ != null) {
          return screenBuilder_.getMessageOrBuilder();
        } else {
          return screen_ == null ?
              ScreenMessage.Screen.getDefaultInstance() : screen_;
        }
      }
      /**
       * <code>.Screen screen = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ScreenMessage.Screen, ScreenMessage.Screen.Builder, ScreenMessage.ScreenOrBuilder> 
          getScreenFieldBuilder() {
        if (screenBuilder_ == null) {
          screenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ScreenMessage.Screen, ScreenMessage.Screen.Builder, ScreenMessage.ScreenOrBuilder>(
                  getScreen(),
                  getParentForChildren(),
                  isClean());
          screen_ = null;
        }
        return screenBuilder_;
      }

      private KeyboardMessage.Keyboard keyboard_;
      private com.google.protobuf.SingleFieldBuilderV3<
          KeyboardMessage.Keyboard, KeyboardMessage.Keyboard.Builder, KeyboardMessage.KeyboardOrBuilder> keyboardBuilder_;
      /**
       * <code>.Keyboard keyboard = 9;</code>
       * @return Whether the keyboard field is set.
       */
      public boolean hasKeyboard() {
        return keyboardBuilder_ != null || keyboard_ != null;
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       * @return The keyboard.
       */
      public KeyboardMessage.Keyboard getKeyboard() {
        if (keyboardBuilder_ == null) {
          return keyboard_ == null ? KeyboardMessage.Keyboard.getDefaultInstance() : keyboard_;
        } else {
          return keyboardBuilder_.getMessage();
        }
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      public Builder setKeyboard(KeyboardMessage.Keyboard value) {
        if (keyboardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          keyboard_ = value;
          onChanged();
        } else {
          keyboardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      public Builder setKeyboard(
          KeyboardMessage.Keyboard.Builder builderForValue) {
        if (keyboardBuilder_ == null) {
          keyboard_ = builderForValue.build();
          onChanged();
        } else {
          keyboardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      public Builder mergeKeyboard(KeyboardMessage.Keyboard value) {
        if (keyboardBuilder_ == null) {
          if (keyboard_ != null) {
            keyboard_ =
              KeyboardMessage.Keyboard.newBuilder(keyboard_).mergeFrom(value).buildPartial();
          } else {
            keyboard_ = value;
          }
          onChanged();
        } else {
          keyboardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      public Builder clearKeyboard() {
        if (keyboardBuilder_ == null) {
          keyboard_ = null;
          onChanged();
        } else {
          keyboard_ = null;
          keyboardBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      public KeyboardMessage.Keyboard.Builder getKeyboardBuilder() {
        
        onChanged();
        return getKeyboardFieldBuilder().getBuilder();
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      public KeyboardMessage.KeyboardOrBuilder getKeyboardOrBuilder() {
        if (keyboardBuilder_ != null) {
          return keyboardBuilder_.getMessageOrBuilder();
        } else {
          return keyboard_ == null ?
              KeyboardMessage.Keyboard.getDefaultInstance() : keyboard_;
        }
      }
      /**
       * <code>.Keyboard keyboard = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          KeyboardMessage.Keyboard, KeyboardMessage.Keyboard.Builder, KeyboardMessage.KeyboardOrBuilder> 
          getKeyboardFieldBuilder() {
        if (keyboardBuilder_ == null) {
          keyboardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              KeyboardMessage.Keyboard, KeyboardMessage.Keyboard.Builder, KeyboardMessage.KeyboardOrBuilder>(
                  getKeyboard(),
                  getParentForChildren(),
                  isClean());
          keyboard_ = null;
        }
        return keyboardBuilder_;
      }

      /**
       * <code>double weight_kg = 10;</code>
       * @return Whether the weightKg field is set.
       */
      public boolean hasWeightKg() {
        return weightCase_ == 10;
      }
      /**
       * <code>double weight_kg = 10;</code>
       * @return The weightKg.
       */
      public double getWeightKg() {
        if (weightCase_ == 10) {
          return (Double) weight_;
        }
        return 0D;
      }
      /**
       * <code>double weight_kg = 10;</code>
       * @param value The weightKg to set.
       * @return This builder for chaining.
       */
      public Builder setWeightKg(double value) {
        weightCase_ = 10;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight_kg = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeightKg() {
        if (weightCase_ == 10) {
          weightCase_ = 0;
          weight_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>double weight_lb = 11;</code>
       * @return Whether the weightLb field is set.
       */
      public boolean hasWeightLb() {
        return weightCase_ == 11;
      }
      /**
       * <code>double weight_lb = 11;</code>
       * @return The weightLb.
       */
      public double getWeightLb() {
        if (weightCase_ == 11) {
          return (Double) weight_;
        }
        return 0D;
      }
      /**
       * <code>double weight_lb = 11;</code>
       * @param value The weightLb to set.
       * @return This builder for chaining.
       */
      public Builder setWeightLb(double value) {
        weightCase_ = 11;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight_lb = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeightLb() {
        if (weightCase_ == 11) {
          weightCase_ = 0;
          weight_ = null;
          onChanged();
        }
        return this;
      }

      private double priceUsd_ ;
      /**
       * <code>double price_usd = 12;</code>
       * @return The priceUsd.
       */
      @Override
      public double getPriceUsd() {
        return priceUsd_;
      }
      /**
       * <code>double price_usd = 12;</code>
       * @param value The priceUsd to set.
       * @return This builder for chaining.
       */
      public Builder setPriceUsd(double value) {
        
        priceUsd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price_usd = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceUsd() {
        
        priceUsd_ = 0D;
        onChanged();
        return this;
      }

      private int releaseYear_ ;
      /**
       * <code>uint32 release_year = 13;</code>
       * @return The releaseYear.
       */
      @Override
      public int getReleaseYear() {
        return releaseYear_;
      }
      /**
       * <code>uint32 release_year = 13;</code>
       * @param value The releaseYear to set.
       * @return This builder for chaining.
       */
      public Builder setReleaseYear(int value) {
        
        releaseYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 release_year = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearReleaseYear() {
        
        releaseYear_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp updatedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return updatedAtBuilder_ != null || updatedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       * @return The updatedAt.
       */
      public com.google.protobuf.Timestamp getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (updatedAt_ != null) {
            updatedAt_ =
              com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
          } else {
            updatedAt_ = value;
          }
          onChanged();
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder clearUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
          onChanged();
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
        
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Laptop)
    }

    // @@protoc_insertion_point(class_scope:Laptop)
    private static final Laptop DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Laptop();
    }

    public static Laptop getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Laptop>
        PARSER = new com.google.protobuf.AbstractParser<Laptop>() {
      @Override
      public Laptop parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Laptop(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Laptop> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Laptop> getParserForType() {
      return PARSER;
    }

    @Override
    public Laptop getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Laptop_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Laptop_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024laptop_message.proto\032\024memory_message.p" +
      "roto\032\027processor-message.proto\032\025storage_m" +
      "essage.proto\032\024screen_message.proto\032\026keyb" +
      "oard_message.proto\032\037google/protobuf/time" +
      "stamp.proto\"\315\002\n\006Laptop\022\n\n\002id\030\001 \001(\t\022\r\n\005br" +
      "and\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\021\n\003cpu\030\004 \001(\0132\004.C" +
      "PU\022\024\n\003ram\030\005 \001(\0132\007.Memory\022\022\n\004gpus\030\006 \003(\0132\004" +
      ".GPU\022\032\n\010storages\030\007 \003(\0132\010.Storage\022\027\n\006scre" +
      "en\030\010 \001(\0132\007.Screen\022\033\n\010keyboard\030\t \001(\0132\t.Ke" +
      "yboard\022\023\n\tweight_kg\030\n \001(\001H\000\022\023\n\tweight_lb" +
      "\030\013 \001(\001H\000\022\021\n\tprice_usd\030\014 \001(\001\022\024\n\014release_y" +
      "ear\030\r \001(\r\022.\n\nupdated_at\030\016 \001(\0132\032.google.p" +
      "rotobuf.TimestampB\010\n\006weightb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MemoryMessage.getDescriptor(),
          ProcessorMessage.getDescriptor(),
          StorageMessage.getDescriptor(),
          ScreenMessage.getDescriptor(),
          KeyboardMessage.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Laptop_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Laptop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Laptop_descriptor,
        new String[] { "Id", "Brand", "Name", "Cpu", "Ram", "Gpus", "Storages", "Screen", "Keyboard", "WeightKg", "WeightLb", "PriceUsd", "ReleaseYear", "UpdatedAt", "Weight", });
    MemoryMessage.getDescriptor();
    ProcessorMessage.getDescriptor();
    StorageMessage.getDescriptor();
    ScreenMessage.getDescriptor();
    KeyboardMessage.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
