package com.implementsfun.protoj;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processor-message.proto

public final class ProcessorMessage {
  private ProcessorMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CPUOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CPU)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    String getBrand();
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 number_cores = 3;</code>
     * @return The numberCores.
     */
    int getNumberCores();

    /**
     * <code>uint32 number_threads = 4;</code>
     * @return The numberThreads.
     */
    int getNumberThreads();

    /**
     * <code>double min_ghz = 5;</code>
     * @return The minGhz.
     */
    double getMinGhz();

    /**
     * <code>double max_ghz = 6;</code>
     * @return The maxGhz.
     */
    double getMaxGhz();
  }
  /**
   * Protobuf type {@code CPU}
   */
  public static final class CPU extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CPU)
      CPUOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CPU.newBuilder() to construct.
    private CPU(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CPU() {
      brand_ = "";
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CPU();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CPU(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              numberCores_ = input.readUInt32();
              break;
            }
            case 32: {

              numberThreads_ = input.readUInt32();
              break;
            }
            case 41: {

              minGhz_ = input.readDouble();
              break;
            }
            case 49: {

              maxGhz_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessorMessage.internal_static_CPU_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessorMessage.internal_static_CPU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CPU.class, Builder.class);
    }

    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile Object brand_;
    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    @Override
    public String getBrand() {
      Object ref = brand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    @Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_CORES_FIELD_NUMBER = 3;
    private int numberCores_;
    /**
     * <code>uint32 number_cores = 3;</code>
     * @return The numberCores.
     */
    @Override
    public int getNumberCores() {
      return numberCores_;
    }

    public static final int NUMBER_THREADS_FIELD_NUMBER = 4;
    private int numberThreads_;
    /**
     * <code>uint32 number_threads = 4;</code>
     * @return The numberThreads.
     */
    @Override
    public int getNumberThreads() {
      return numberThreads_;
    }

    public static final int MIN_GHZ_FIELD_NUMBER = 5;
    private double minGhz_;
    /**
     * <code>double min_ghz = 5;</code>
     * @return The minGhz.
     */
    @Override
    public double getMinGhz() {
      return minGhz_;
    }

    public static final int MAX_GHZ_FIELD_NUMBER = 6;
    private double maxGhz_;
    /**
     * <code>double max_ghz = 6;</code>
     * @return The maxGhz.
     */
    @Override
    public double getMaxGhz() {
      return maxGhz_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (numberCores_ != 0) {
        output.writeUInt32(3, numberCores_);
      }
      if (numberThreads_ != 0) {
        output.writeUInt32(4, numberThreads_);
      }
      if (Double.doubleToRawLongBits(minGhz_) != 0) {
        output.writeDouble(5, minGhz_);
      }
      if (Double.doubleToRawLongBits(maxGhz_) != 0) {
        output.writeDouble(6, maxGhz_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (numberCores_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, numberCores_);
      }
      if (numberThreads_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, numberThreads_);
      }
      if (Double.doubleToRawLongBits(minGhz_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, minGhz_);
      }
      if (Double.doubleToRawLongBits(maxGhz_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, maxGhz_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CPU)) {
        return super.equals(obj);
      }
      CPU other = (CPU) obj;

      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getNumberCores()
          != other.getNumberCores()) return false;
      if (getNumberThreads()
          != other.getNumberThreads()) return false;
      if (Double.doubleToLongBits(getMinGhz())
          != Double.doubleToLongBits(
              other.getMinGhz())) return false;
      if (Double.doubleToLongBits(getMaxGhz())
          != Double.doubleToLongBits(
              other.getMaxGhz())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + NUMBER_CORES_FIELD_NUMBER;
      hash = (53 * hash) + getNumberCores();
      hash = (37 * hash) + NUMBER_THREADS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberThreads();
      hash = (37 * hash) + MIN_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMinGhz()));
      hash = (37 * hash) + MAX_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMaxGhz()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CPU parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPU parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPU parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPU parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPU parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPU parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPU parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPU parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPU parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CPU parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPU parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPU parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CPU prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CPU}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CPU)
        CPUOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProcessorMessage.internal_static_CPU_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProcessorMessage.internal_static_CPU_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CPU.class, Builder.class);
      }

      // Construct using ProcessorMessage.CPU.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        brand_ = "";

        name_ = "";

        numberCores_ = 0;

        numberThreads_ = 0;

        minGhz_ = 0D;

        maxGhz_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProcessorMessage.internal_static_CPU_descriptor;
      }

      @Override
      public CPU getDefaultInstanceForType() {
        return CPU.getDefaultInstance();
      }

      @Override
      public CPU build() {
        CPU result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CPU buildPartial() {
        CPU result = new CPU(this);
        result.brand_ = brand_;
        result.name_ = name_;
        result.numberCores_ = numberCores_;
        result.numberThreads_ = numberThreads_;
        result.minGhz_ = minGhz_;
        result.maxGhz_ = maxGhz_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CPU) {
          return mergeFrom((CPU)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CPU other) {
        if (other == CPU.getDefaultInstance()) return this;
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getNumberCores() != 0) {
          setNumberCores(other.getNumberCores());
        }
        if (other.getNumberThreads() != 0) {
          setNumberThreads(other.getNumberThreads());
        }
        if (other.getMinGhz() != 0D) {
          setMinGhz(other.getMinGhz());
        }
        if (other.getMaxGhz() != 0D) {
          setMaxGhz(other.getMaxGhz());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CPU parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CPU) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object brand_ = "";
      /**
       * <code>string brand = 1;</code>
       * @return The brand.
       */
      public String getBrand() {
        Object ref = brand_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int numberCores_ ;
      /**
       * <code>uint32 number_cores = 3;</code>
       * @return The numberCores.
       */
      @Override
      public int getNumberCores() {
        return numberCores_;
      }
      /**
       * <code>uint32 number_cores = 3;</code>
       * @param value The numberCores to set.
       * @return This builder for chaining.
       */
      public Builder setNumberCores(int value) {
        
        numberCores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_cores = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberCores() {
        
        numberCores_ = 0;
        onChanged();
        return this;
      }

      private int numberThreads_ ;
      /**
       * <code>uint32 number_threads = 4;</code>
       * @return The numberThreads.
       */
      @Override
      public int getNumberThreads() {
        return numberThreads_;
      }
      /**
       * <code>uint32 number_threads = 4;</code>
       * @param value The numberThreads to set.
       * @return This builder for chaining.
       */
      public Builder setNumberThreads(int value) {
        
        numberThreads_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_threads = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberThreads() {
        
        numberThreads_ = 0;
        onChanged();
        return this;
      }

      private double minGhz_ ;
      /**
       * <code>double min_ghz = 5;</code>
       * @return The minGhz.
       */
      @Override
      public double getMinGhz() {
        return minGhz_;
      }
      /**
       * <code>double min_ghz = 5;</code>
       * @param value The minGhz to set.
       * @return This builder for chaining.
       */
      public Builder setMinGhz(double value) {
        
        minGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double min_ghz = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinGhz() {
        
        minGhz_ = 0D;
        onChanged();
        return this;
      }

      private double maxGhz_ ;
      /**
       * <code>double max_ghz = 6;</code>
       * @return The maxGhz.
       */
      @Override
      public double getMaxGhz() {
        return maxGhz_;
      }
      /**
       * <code>double max_ghz = 6;</code>
       * @param value The maxGhz to set.
       * @return This builder for chaining.
       */
      public Builder setMaxGhz(double value) {
        
        maxGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double max_ghz = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxGhz() {
        
        maxGhz_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CPU)
    }

    // @@protoc_insertion_point(class_scope:CPU)
    private static final CPU DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPU();
    }

    public static CPU getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPU>
        PARSER = new com.google.protobuf.AbstractParser<CPU>() {
      @Override
      public CPU parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPU(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CPU> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CPU> getParserForType() {
      return PARSER;
    }

    @Override
    public CPU getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GPUOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GPU)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    String getBrand();
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double min_ghz = 3;</code>
     * @return The minGhz.
     */
    double getMinGhz();

    /**
     * <code>double max_ghz = 4;</code>
     * @return The maxGhz.
     */
    double getMaxGhz();

    /**
     * <code>.Memory memory = 5;</code>
     * @return Whether the memory field is set.
     */
    boolean hasMemory();
    /**
     * <code>.Memory memory = 5;</code>
     * @return The memory.
     */
    MemoryMessage.Memory getMemory();
    /**
     * <code>.Memory memory = 5;</code>
     */
    MemoryMessage.MemoryOrBuilder getMemoryOrBuilder();
  }
  /**
   * Protobuf type {@code GPU}
   */
  public static final class GPU extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GPU)
      GPUOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GPU.newBuilder() to construct.
    private GPU(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GPU() {
      brand_ = "";
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GPU();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GPU(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 25: {

              minGhz_ = input.readDouble();
              break;
            }
            case 33: {

              maxGhz_ = input.readDouble();
              break;
            }
            case 42: {
              MemoryMessage.Memory.Builder subBuilder = null;
              if (memory_ != null) {
                subBuilder = memory_.toBuilder();
              }
              memory_ = input.readMessage(MemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(memory_);
                memory_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessorMessage.internal_static_GPU_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessorMessage.internal_static_GPU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GPU.class, Builder.class);
    }

    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile Object brand_;
    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    @Override
    public String getBrand() {
      Object ref = brand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    @Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIN_GHZ_FIELD_NUMBER = 3;
    private double minGhz_;
    /**
     * <code>double min_ghz = 3;</code>
     * @return The minGhz.
     */
    @Override
    public double getMinGhz() {
      return minGhz_;
    }

    public static final int MAX_GHZ_FIELD_NUMBER = 4;
    private double maxGhz_;
    /**
     * <code>double max_ghz = 4;</code>
     * @return The maxGhz.
     */
    @Override
    public double getMaxGhz() {
      return maxGhz_;
    }

    public static final int MEMORY_FIELD_NUMBER = 5;
    private MemoryMessage.Memory memory_;
    /**
     * <code>.Memory memory = 5;</code>
     * @return Whether the memory field is set.
     */
    @Override
    public boolean hasMemory() {
      return memory_ != null;
    }
    /**
     * <code>.Memory memory = 5;</code>
     * @return The memory.
     */
    @Override
    public MemoryMessage.Memory getMemory() {
      return memory_ == null ? MemoryMessage.Memory.getDefaultInstance() : memory_;
    }
    /**
     * <code>.Memory memory = 5;</code>
     */
    @Override
    public MemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
      return getMemory();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (Double.doubleToRawLongBits(minGhz_) != 0) {
        output.writeDouble(3, minGhz_);
      }
      if (Double.doubleToRawLongBits(maxGhz_) != 0) {
        output.writeDouble(4, maxGhz_);
      }
      if (memory_ != null) {
        output.writeMessage(5, getMemory());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (Double.doubleToRawLongBits(minGhz_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, minGhz_);
      }
      if (Double.doubleToRawLongBits(maxGhz_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxGhz_);
      }
      if (memory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMemory());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GPU)) {
        return super.equals(obj);
      }
      GPU other = (GPU) obj;

      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (Double.doubleToLongBits(getMinGhz())
          != Double.doubleToLongBits(
              other.getMinGhz())) return false;
      if (Double.doubleToLongBits(getMaxGhz())
          != Double.doubleToLongBits(
              other.getMaxGhz())) return false;
      if (hasMemory() != other.hasMemory()) return false;
      if (hasMemory()) {
        if (!getMemory()
            .equals(other.getMemory())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + MIN_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMinGhz()));
      hash = (37 * hash) + MAX_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMaxGhz()));
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + getMemory().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GPU parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GPU parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GPU parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GPU parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GPU parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GPU parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GPU parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GPU parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GPU parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GPU parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GPU parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GPU parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GPU prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GPU}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GPU)
        GPUOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProcessorMessage.internal_static_GPU_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProcessorMessage.internal_static_GPU_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GPU.class, Builder.class);
      }

      // Construct using ProcessorMessage.GPU.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        brand_ = "";

        name_ = "";

        minGhz_ = 0D;

        maxGhz_ = 0D;

        if (memoryBuilder_ == null) {
          memory_ = null;
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProcessorMessage.internal_static_GPU_descriptor;
      }

      @Override
      public GPU getDefaultInstanceForType() {
        return GPU.getDefaultInstance();
      }

      @Override
      public GPU build() {
        GPU result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GPU buildPartial() {
        GPU result = new GPU(this);
        result.brand_ = brand_;
        result.name_ = name_;
        result.minGhz_ = minGhz_;
        result.maxGhz_ = maxGhz_;
        if (memoryBuilder_ == null) {
          result.memory_ = memory_;
        } else {
          result.memory_ = memoryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GPU) {
          return mergeFrom((GPU)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GPU other) {
        if (other == GPU.getDefaultInstance()) return this;
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getMinGhz() != 0D) {
          setMinGhz(other.getMinGhz());
        }
        if (other.getMaxGhz() != 0D) {
          setMaxGhz(other.getMaxGhz());
        }
        if (other.hasMemory()) {
          mergeMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GPU parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GPU) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object brand_ = "";
      /**
       * <code>string brand = 1;</code>
       * @return The brand.
       */
      public String getBrand() {
        Object ref = brand_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double minGhz_ ;
      /**
       * <code>double min_ghz = 3;</code>
       * @return The minGhz.
       */
      @Override
      public double getMinGhz() {
        return minGhz_;
      }
      /**
       * <code>double min_ghz = 3;</code>
       * @param value The minGhz to set.
       * @return This builder for chaining.
       */
      public Builder setMinGhz(double value) {
        
        minGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double min_ghz = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinGhz() {
        
        minGhz_ = 0D;
        onChanged();
        return this;
      }

      private double maxGhz_ ;
      /**
       * <code>double max_ghz = 4;</code>
       * @return The maxGhz.
       */
      @Override
      public double getMaxGhz() {
        return maxGhz_;
      }
      /**
       * <code>double max_ghz = 4;</code>
       * @param value The maxGhz to set.
       * @return This builder for chaining.
       */
      public Builder setMaxGhz(double value) {
        
        maxGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double max_ghz = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxGhz() {
        
        maxGhz_ = 0D;
        onChanged();
        return this;
      }

      private MemoryMessage.Memory memory_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> memoryBuilder_;
      /**
       * <code>.Memory memory = 5;</code>
       * @return Whether the memory field is set.
       */
      public boolean hasMemory() {
        return memoryBuilder_ != null || memory_ != null;
      }
      /**
       * <code>.Memory memory = 5;</code>
       * @return The memory.
       */
      public MemoryMessage.Memory getMemory() {
        if (memoryBuilder_ == null) {
          return memory_ == null ? MemoryMessage.Memory.getDefaultInstance() : memory_;
        } else {
          return memoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      public Builder setMemory(MemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memory_ = value;
          onChanged();
        } else {
          memoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      public Builder setMemory(
          MemoryMessage.Memory.Builder builderForValue) {
        if (memoryBuilder_ == null) {
          memory_ = builderForValue.build();
          onChanged();
        } else {
          memoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      public Builder mergeMemory(MemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (memory_ != null) {
            memory_ =
              MemoryMessage.Memory.newBuilder(memory_).mergeFrom(value).buildPartial();
          } else {
            memory_ = value;
          }
          onChanged();
        } else {
          memoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      public Builder clearMemory() {
        if (memoryBuilder_ == null) {
          memory_ = null;
          onChanged();
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      public MemoryMessage.Memory.Builder getMemoryBuilder() {
        
        onChanged();
        return getMemoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      public MemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
        if (memoryBuilder_ != null) {
          return memoryBuilder_.getMessageOrBuilder();
        } else {
          return memory_ == null ?
              MemoryMessage.Memory.getDefaultInstance() : memory_;
        }
      }
      /**
       * <code>.Memory memory = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> 
          getMemoryFieldBuilder() {
        if (memoryBuilder_ == null) {
          memoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder>(
                  getMemory(),
                  getParentForChildren(),
                  isClean());
          memory_ = null;
        }
        return memoryBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GPU)
    }

    // @@protoc_insertion_point(class_scope:GPU)
    private static final GPU DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GPU();
    }

    public static GPU getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GPU>
        PARSER = new com.google.protobuf.AbstractParser<GPU>() {
      @Override
      public GPU parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GPU(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GPU> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GPU> getParserForType() {
      return PARSER;
    }

    @Override
    public GPU getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CPU_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CPU_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GPU_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GPU_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027processor-message.proto\032\024memory_messag" +
      "e.proto\"r\n\003CPU\022\r\n\005brand\030\001 \001(\t\022\014\n\004name\030\002 " +
      "\001(\t\022\024\n\014number_cores\030\003 \001(\r\022\026\n\016number_thre" +
      "ads\030\004 \001(\r\022\017\n\007min_ghz\030\005 \001(\001\022\017\n\007max_ghz\030\006 " +
      "\001(\001\"]\n\003GPU\022\r\n\005brand\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022" +
      "\017\n\007min_ghz\030\003 \001(\001\022\017\n\007max_ghz\030\004 \001(\001\022\027\n\006mem" +
      "ory\030\005 \001(\0132\007.Memoryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MemoryMessage.getDescriptor(),
        });
    internal_static_CPU_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CPU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CPU_descriptor,
        new String[] { "Brand", "Name", "NumberCores", "NumberThreads", "MinGhz", "MaxGhz", });
    internal_static_GPU_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GPU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GPU_descriptor,
        new String[] { "Brand", "Name", "MinGhz", "MaxGhz", "Memory", });
    MemoryMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
