package com.implementsfun.protoj;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_message.proto

public final class StorageMessage {
  private StorageMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Storage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Storage.Driver driver = 1;</code>
     * @return The enum numeric value on the wire for driver.
     */
    int getDriverValue();
    /**
     * <code>.Storage.Driver driver = 1;</code>
     * @return The driver.
     */
    Storage.Driver getDriver();

    /**
     * <code>.Memory memory = 2;</code>
     * @return Whether the memory field is set.
     */
    boolean hasMemory();
    /**
     * <code>.Memory memory = 2;</code>
     * @return The memory.
     */
    MemoryMessage.Memory getMemory();
    /**
     * <code>.Memory memory = 2;</code>
     */
    MemoryMessage.MemoryOrBuilder getMemoryOrBuilder();
  }
  /**
   * Protobuf type {@code Storage}
   */
  public static final class Storage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Storage)
      StorageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Storage.newBuilder() to construct.
    private Storage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Storage() {
      driver_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Storage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Storage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              driver_ = rawValue;
              break;
            }
            case 18: {
              MemoryMessage.Memory.Builder subBuilder = null;
              if (memory_ != null) {
                subBuilder = memory_.toBuilder();
              }
              memory_ = input.readMessage(MemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(memory_);
                memory_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StorageMessage.internal_static_Storage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StorageMessage.internal_static_Storage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Storage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Storage.Driver}
     */
    public enum Driver
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>HDD = 1;</code>
       */
      HDD(1),
      /**
       * <code>SSD = 2;</code>
       */
      SSD(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>HDD = 1;</code>
       */
      public static final int HDD_VALUE = 1;
      /**
       * <code>SSD = 2;</code>
       */
      public static final int SSD_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Driver valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Driver forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return HDD;
          case 2: return SSD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Driver>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Driver> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Driver>() {
              public Driver findValueByNumber(int number) {
                return Driver.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Storage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Driver[] VALUES = values();

      public static Driver valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Driver(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Storage.Driver)
    }

    public static final int DRIVER_FIELD_NUMBER = 1;
    private int driver_;
    /**
     * <code>.Storage.Driver driver = 1;</code>
     * @return The enum numeric value on the wire for driver.
     */
    @Override public int getDriverValue() {
      return driver_;
    }
    /**
     * <code>.Storage.Driver driver = 1;</code>
     * @return The driver.
     */
    @Override public Driver getDriver() {
      @SuppressWarnings("deprecation")
      Driver result = Driver.valueOf(driver_);
      return result == null ? Driver.UNRECOGNIZED : result;
    }

    public static final int MEMORY_FIELD_NUMBER = 2;
    private MemoryMessage.Memory memory_;
    /**
     * <code>.Memory memory = 2;</code>
     * @return Whether the memory field is set.
     */
    @Override
    public boolean hasMemory() {
      return memory_ != null;
    }
    /**
     * <code>.Memory memory = 2;</code>
     * @return The memory.
     */
    @Override
    public MemoryMessage.Memory getMemory() {
      return memory_ == null ? MemoryMessage.Memory.getDefaultInstance() : memory_;
    }
    /**
     * <code>.Memory memory = 2;</code>
     */
    @Override
    public MemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
      return getMemory();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (driver_ != Driver.UNKNOWN.getNumber()) {
        output.writeEnum(1, driver_);
      }
      if (memory_ != null) {
        output.writeMessage(2, getMemory());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (driver_ != Driver.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, driver_);
      }
      if (memory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMemory());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Storage)) {
        return super.equals(obj);
      }
      Storage other = (Storage) obj;

      if (driver_ != other.driver_) return false;
      if (hasMemory() != other.hasMemory()) return false;
      if (hasMemory()) {
        if (!getMemory()
            .equals(other.getMemory())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DRIVER_FIELD_NUMBER;
      hash = (53 * hash) + driver_;
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + getMemory().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Storage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Storage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Storage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Storage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Storage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Storage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Storage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Storage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Storage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Storage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Storage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Storage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Storage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Storage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Storage)
        StorageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StorageMessage.internal_static_Storage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StorageMessage.internal_static_Storage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Storage.class, Builder.class);
      }

      // Construct using StorageMessage.Storage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        driver_ = 0;

        if (memoryBuilder_ == null) {
          memory_ = null;
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StorageMessage.internal_static_Storage_descriptor;
      }

      @Override
      public Storage getDefaultInstanceForType() {
        return Storage.getDefaultInstance();
      }

      @Override
      public Storage build() {
        Storage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Storage buildPartial() {
        Storage result = new Storage(this);
        result.driver_ = driver_;
        if (memoryBuilder_ == null) {
          result.memory_ = memory_;
        } else {
          result.memory_ = memoryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Storage) {
          return mergeFrom((Storage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Storage other) {
        if (other == Storage.getDefaultInstance()) return this;
        if (other.driver_ != 0) {
          setDriverValue(other.getDriverValue());
        }
        if (other.hasMemory()) {
          mergeMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Storage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Storage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int driver_ = 0;
      /**
       * <code>.Storage.Driver driver = 1;</code>
       * @return The enum numeric value on the wire for driver.
       */
      @Override public int getDriverValue() {
        return driver_;
      }
      /**
       * <code>.Storage.Driver driver = 1;</code>
       * @param value The enum numeric value on the wire for driver to set.
       * @return This builder for chaining.
       */
      public Builder setDriverValue(int value) {
        
        driver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Storage.Driver driver = 1;</code>
       * @return The driver.
       */
      @Override
      public Driver getDriver() {
        @SuppressWarnings("deprecation")
        Driver result = Driver.valueOf(driver_);
        return result == null ? Driver.UNRECOGNIZED : result;
      }
      /**
       * <code>.Storage.Driver driver = 1;</code>
       * @param value The driver to set.
       * @return This builder for chaining.
       */
      public Builder setDriver(Driver value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        driver_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Storage.Driver driver = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDriver() {
        
        driver_ = 0;
        onChanged();
        return this;
      }

      private MemoryMessage.Memory memory_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> memoryBuilder_;
      /**
       * <code>.Memory memory = 2;</code>
       * @return Whether the memory field is set.
       */
      public boolean hasMemory() {
        return memoryBuilder_ != null || memory_ != null;
      }
      /**
       * <code>.Memory memory = 2;</code>
       * @return The memory.
       */
      public MemoryMessage.Memory getMemory() {
        if (memoryBuilder_ == null) {
          return memory_ == null ? MemoryMessage.Memory.getDefaultInstance() : memory_;
        } else {
          return memoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      public Builder setMemory(MemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memory_ = value;
          onChanged();
        } else {
          memoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      public Builder setMemory(
          MemoryMessage.Memory.Builder builderForValue) {
        if (memoryBuilder_ == null) {
          memory_ = builderForValue.build();
          onChanged();
        } else {
          memoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      public Builder mergeMemory(MemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (memory_ != null) {
            memory_ =
              MemoryMessage.Memory.newBuilder(memory_).mergeFrom(value).buildPartial();
          } else {
            memory_ = value;
          }
          onChanged();
        } else {
          memoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      public Builder clearMemory() {
        if (memoryBuilder_ == null) {
          memory_ = null;
          onChanged();
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      public MemoryMessage.Memory.Builder getMemoryBuilder() {
        
        onChanged();
        return getMemoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      public MemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
        if (memoryBuilder_ != null) {
          return memoryBuilder_.getMessageOrBuilder();
        } else {
          return memory_ == null ?
              MemoryMessage.Memory.getDefaultInstance() : memory_;
        }
      }
      /**
       * <code>.Memory memory = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder> 
          getMemoryFieldBuilder() {
        if (memoryBuilder_ == null) {
          memoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MemoryMessage.Memory, MemoryMessage.Memory.Builder, MemoryMessage.MemoryOrBuilder>(
                  getMemory(),
                  getParentForChildren(),
                  isClean());
          memory_ = null;
        }
        return memoryBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Storage)
    }

    // @@protoc_insertion_point(class_scope:Storage)
    private static final Storage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Storage();
    }

    public static Storage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Storage>
        PARSER = new com.google.protobuf.AbstractParser<Storage>() {
      @Override
      public Storage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Storage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Storage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Storage> getParserForType() {
      return PARSER;
    }

    @Override
    public Storage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025storage_message.proto\032\024memory_message." +
      "proto\"l\n\007Storage\022\037\n\006driver\030\001 \001(\0162\017.Stora" +
      "ge.Driver\022\027\n\006memory\030\002 \001(\0132\007.Memory\"\'\n\006Dr" +
      "iver\022\013\n\007UNKNOWN\020\000\022\007\n\003HDD\020\001\022\007\n\003SSD\020\002b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MemoryMessage.getDescriptor(),
        });
    internal_static_Storage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Storage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_descriptor,
        new String[] { "Driver", "Memory", });
    MemoryMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
